# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 9cd612a06d08b7c7f9f14e03740affb59994021f3273f4a226906b4b7150794e9fa4cfa284cf387a713021ac1c0e288e7c875d8ab7beb54622d76af723945d46
  domain_name: localhost:3000

test:
  secret_key_base: a5d27cd1ed496fbaead82eb9a14ffa42a9b1cf9eca37df315cc063add99ab8a84a67e5c78e8a98c3a580f05cb6dde772966bf62898e2196c44250779521d8362

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  domain_name: <%= ENV["DOMAIN_NAME"] %>
